### ISSUE TITLE
Setting forwarding.fluentd.ssl=false fails to deploy

### ISSUE THREAD

**Issue by bpayton** [sabre1041/openshift-logforwarding-splunk#11]
Following the instructions in the REAME here https://github.com/sabre1041/openshift-logforwarding-splunk#fluentd, I set ssl=false to disable SSL for the communication between OpenShift and the logforwarder.

snippet of values.yml:
```
forwarding:
  fluentd:
    port: 24224
    sharedkey: splunkforwarding
    passphrase: ""
    ssl: false
    #caFile: files/default-openshift-logging-fluentd.crt
    #keyFile: files/default-openshift-logging-fluentd.key
```

However, when deploying the chart, the pod never comes up and produces this error:
`MountVolume.SetUp failed for volume "openshift-logforwarding-splunk" : references non-existent secret key: forwarder-tls.crt`

This is on OpenShift 4.7. Thanks!
